project_id = "suehzckzvcqtfndaypmo"

[functions.register-donor]
verify_jwt = false

[functions.register-organization]
verify_jwt = false

[functions.submit-food-donation]
verify_jwt = false

[functions.create-donation-request]
verify_jwt = false
